// Precompute the derived bundle + identities that the page also computes
// in-browser. `node tools/build-derived.mjs` writes derived/bundle/** and
// derived/identities.json. Cross-check with `python3 tools/derived_vectors.py`.
import { createRequire } from "node:module";
import { readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const demo = join(here, "..");
const A = require(join(demo, "adapter.js"));

const trace = JSON.parse(readFileSync(join(demo, "traces/bqaa-germany.json"), "utf8"));
const out = A.adapt(trace);
const manifests = {};
for (const n of ["canonicalization-manifest", "semantic-config", "resolver-manifest", "vocabulary-manifest"])
  manifests[n] = new Uint8Array(readFileSync(join(demo, "fixture/golden/manifests", n + ".json")));
const ids = A.computeIdentities(out.files, out.constants, manifests);

const bundleDir = join(demo, "derived/bundle");
rmSync(bundleDir, { recursive: true, force: true });
for (const [p, text] of Object.entries(out.files)) {
  mkdirSync(dirname(join(bundleDir, p)), { recursive: true });
  writeFileSync(join(bundleDir, p), text, "utf8");
}
const identities = {
  _comment: "DERIVED / DEMO. Generated by tools/build-derived.mjs from traces/bqaa-germany.json via adapter.js + hash.js (PROFILE.md rules). Independently re-derived by tools/derived_vectors.py. Not canonical authoring; distinct bundle_key from cymbal-finance-core. All names fictional.",
  inputs: {
    ...out.constants,
    compile_manifests: "fixture/golden/manifests (same compile semantics as the authored fixture)",
    trace: "traces/bqaa-germany.json",
    observed_publication_id: out.observation.observed_publication_id
  },
  ...ids,
  demo_envelope_id: A.demoEnvelopeId(ids.publication_id)
};
writeFileSync(join(demo, "derived/identities.json"), JSON.stringify(identities, null, 2) + "\n");
console.log(Object.keys(out.files).length + " derived files");
console.log("observation_id  " + ids.observation_id);
console.log("snapshot_id     " + ids.snapshot_id);
console.log("publication_id  " + ids.publication_id);
